### ISSUE TITLE
How to use method_profiler in rails app ?

### ISSUE THREAD

**Issue by fahim-aretove** [change/method_profiler#10]
Hello,

I had studied readme.md but I am not able to find that how to configure method_profiler with rails app. How to  use with rails app ?

Thanks

Best Regards
Fahim Babar Patel

**Comment by EdwinRozario** [comment]
I have used method_profiler with Rspec. Was kinda simple once i figure out how to modify spec_helper. Update the spec_helper with this.

require 'method_profiler'

RSpec.configure do |config|

  config.before (:all) do |spec|
      @file = File.open("performance-test.txt", "a")
      @profiler = MethodProfiler.observe(spec.described_class)
  end

  config.after :all do |spec|
    @file.write @profiler.report.to_s
    @file.close
  end 
   
end

**Comment by drakmail** [comment]
Simplest example:

1. Include in Gemfile `gem "method_profiler"`
2. Use it where it interesting for you:

```ruby
# for ex. in Controller:
def some_action
  profiler = MethodProfiler.observe(Project)
  p = Project.find params[:id]
  p.calculate_something
  puts profile.report
end
```
